import { IBee } from "@shared/interfaces";
import { ChannelType } from "@shared/interfaces";

export const demoSwarm: IBee[] = [
  {
    id: 1,
    ipAddress: "192.168.50.101",
    isOnline: true,
    isApiOn: true,
    name: "Bee 1",
    status: {
      isJackRunning: true,
      isJacktripRunning: true,
    },
    channelType: ChannelType.MONO,
    networkPerformanceMs: 1,
    isActive: true,
    channel1: 1,
  },
  {
    id: 2,
    ipAddress: "192.168.50.102",
    isOnline: true,
    isApiOn: true,
    name: "Bee 2",
    status: {
      isJackRunning: true,
      isJacktripRunning: true,
    },
    channelType: ChannelType.MONO,
    networkPerformanceMs: 1,
    isActive: true,
    channel1: 1,
  },
  {
    id: 3,
    ipAddress: "192.168.50.103",
    isOnline: true,
    isApiOn: true,
    name: "Bee 3",
    status: {
      isJackRunning: true,
      isJacktripRunning: true,
    },
    channelType: ChannelType.MONO,
    networkPerformanceMs: 1,
    isActive: true,
    channel1: 1,
  },
  {
    id: 4,
    ipAddress: "192.168.50.104",
    isOnline: true,
    isApiOn: true,
    name: "Bee 4",
    status: {
      isJackRunning: true,
      isJacktripRunning: true,
    },
    channelType: ChannelType.MONO,
    networkPerformanceMs: 1,
    isActive: true,
    channel1: 1,
  },
  {
    id: 5,
    ipAddress: "192.168.50.105",
    isOnline: true,
    isApiOn: true,
    name: "Bee 5",
    status: {
      isJackRunning: true,
      isJacktripRunning: true,
    },
    channelType: ChannelType.MONO,
    networkPerformanceMs: 1,
    isActive: true,
    channel1: 1,
  },
  {
    id: 6,
    ipAddress: "192.168.50.105",
    isOnline: true,
    isApiOn: true,
    name: "Bee 6",
    status: {
      isJackRunning: true,
      isJacktripRunning: true,
    },
    channelType: ChannelType.MONO,
    networkPerformanceMs: 1,
    isActive: true,
    channel1: 1,
  },
  {
    id: 7,
    ipAddress: "192.168.50.105",
    isOnline: true,
    isApiOn: true,
    name: "Bee 7",
    status: {
      isJackRunning: true,
      isJacktripRunning: true,
    },
    channelType: ChannelType.MONO,
    networkPerformanceMs: 1,
    isActive: true,
    channel1: 1,
  },
  {
    id: 8,
    ipAddress: "192.168.50.105",
    isOnline: true,
    isApiOn: true,
    name: "Bee 8",
    status: {
      isJackRunning: true,
      isJacktripRunning: true,
    },
    channelType: ChannelType.MONO,
    networkPerformanceMs: 1,
    isActive: true,
    channel1: 1,
  },
  {
    id: 9,
    ipAddress: "192.168.50.105",
    isOnline: true,
    isApiOn: true,
    name: "Bee 9",
    status: {
      isJackRunning: true,
      isJacktripRunning: true,
    },
    channelType: ChannelType.MONO,
    networkPerformanceMs: 1,
    isActive: true,
    channel1: 1,
  },
  {
    id: 10,
    ipAddress: "192.168.50.105",
    isOnline: true,
    isApiOn: true,
    name: "Bee 10",
    status: {
      isJackRunning: true,
      isJacktripRunning: true,
    },
    channelType: ChannelType.MONO,
    networkPerformanceMs: 1,
    isActive: true,
    channel1: 1,
  },
  {
    id: 11,
    ipAddress: "192.168.50.105",
    isOnline: true,
    isApiOn: true,
    name: "Bee 11",
    status: {
      isJackRunning: true,
      isJacktripRunning: true,
    },
    channelType: ChannelType.MONO,
    networkPerformanceMs: 1,
    isActive: true,
    channel1: 1,
  },
  {
    id: 12,
    ipAddress: "192.168.50.105",
    isOnline: true,
    isApiOn: true,
    name: "Bee 12",
    status: {
      isJackRunning: true,
      isJacktripRunning: true,
    },
    channelType: ChannelType.MONO,
    networkPerformanceMs: 1,
    isActive: true,
    channel1: 1,
  },
];
