import { AudioScene } from "../shared/interfaces";
import { ChannelType } from "@shared/enums";

export const demoScenes: AudioScene[] = [
  ...Array.from({ length: 100 }, (_, sceneIndex) => ({
    name: [
      "RC_Tree_Speedy",
      "RC_Tree_Silent",
      "RC_Field_Open",
      "RC_Field_Rustling",
      "RC_Meadow_Lush",
      "RC_Meadow_Breezy",
      "Nature_Forest_Mystic",
      "Nature_Forest_Shadowed",
      "Nature_Forest_Singing",
      "Nature_Lake_Shimmering",
      "Nature_Lake_Still",
      "Nature_Lake_Reflecting",
      "Nature_Mountain_Stormy",
      "Nature_Mountain_Windy",
      "Nature_Mountain_Peak",
      "City_Urban_RushHour",
      "City_Urban_Midnight",
      "City_Park_Quiet",
      "City_Park_Daylight",
      "City_Downtown_Busy",
      "City_Downtown_Nightlife",
      "Weather_Snow_Frozen",
      "Weather_Snow_Falling",
      "Weather_Snow_Blizzard",
      "Weather_Storm_Thunder",
      "Weather_Storm_Lightning",
      "Weather_Storm_Downpour",
      "Ocean_Bay_Celestial",
      "Ocean_Bay_Calm",
      "Ocean_Bay_Waves",
      "Ocean_Coastline_Golden",
      "Ocean_Coastline_Sandy",
      "Ocean_Coastline_Rocky",
      "Fantasy_Forest_Enchanted",
      "Fantasy_Forest_Whispering",
      "Fantasy_Island_Lost",
      "Fantasy_Island_Sacred",
      "Fantasy_Island_Mysterious",
      "Fantasy_Cave_Glowing",
      "Fantasy_Cave_Deep",
      "Fantasy_Cave_Secret",
      "Weather_Rain_Gentle",
      "Weather_Rain_Pouring",
      "Weather_Rain_Misty",
      "Weather_Wind_Breezy",
      "Weather_Wind_Gusty",
      "Weather_Wind_Howling",
      "Space_Galaxy_Nebula",
      "Space_Galaxy_Vast",
      "Space_Stars_Bright",
      "Space_Stars_Twinkling",
      "Space_Comet_Fast",
      "Space_Comet_Trail",
      "RC_River_Flowing",
      "RC_River_Calm",
      "RC_River_Rushing",
      "Desert_Dunes_Endless",
      "Desert_Dunes_Rippled",
      "Desert_Oasis_Hidden",
      "Desert_Oasis_Serene",
      "Desert_Canyon_Deep",
      "Desert_Canyon_Shadowed",
      "City_Subway_Rattling",
      "City_Subway_Echoing",
      "City_Rooftop_Vista",
      "City_Rooftop_Sunset",
      "Nature_Falls_Rushing",
      "Nature_Falls_Tranquil",
      "Nature_Falls_Majestic",
      "RC_Pond_Soft",
      "RC_Pond_Reflective",
      "RC_Pond_Rippled",
      "Fantasy_Meadow_Magical",
      "Fantasy_Meadow_Luminous",
      "Fantasy_Meadow_Calm",
      "Weather_Clouds_Drifting",
      "Weather_Clouds_Gathering",
      "Weather_Clouds_Fluffy",
      "Ocean_Reef_Colorful",
      "Ocean_Reef_Quiet",
      "Ocean_Reef_Bustling",
      "Fantasy_Portal_Glowing",
      "Fantasy_Portal_Swirling",
      "Fantasy_Portal_Silent",
      "Space_Asteroid_Field",
      "Space_Asteroid_Belt",
      "Space_Void_Silent",
      "Space_Void_Lonely",
      "Space_Void_Mysterious",
      "Nature_Peak_High",
      "Nature_Peak_Cliffside",
      "Nature_Peak_Sunlit",
      "Fantasy_Forest_Hidden",
      "Fantasy_Forest_Glimmering",
      "RC_Canyon_Narrow",
      "RC_Canyon_Open",
      "RC_Canyon_Windy",
      "City_Alleyway_Shadowed",
      "City_Alleyway_Narrow",
      "City_Alleyway_Quiet",
    ][sceneIndex], // Assigns a unique creative name to each scene
    foundOnBees: Array.from({ length: 16 }, (_, beeIndex) => ({
      id: beeIndex + 1,
      ipAddress: `192.168.50.${101 + beeIndex}`,
      isOnline: true,
      isApiOn: true,
      name: `Bee ${beeIndex + 1}`,
      status: {
        isJackRunning: true,
        isJacktripRunning: true,
      },
      channelType: ChannelType.MONO,
      networkPerformanceMs: Math.floor(Math.random() * 10) + 1, // Random 1-10 ms
      isActive: true,
      channel1: 1,
    })).slice(0, Math.floor(Math.random() * 12) + 5), // Randomly select 5-16 bees for each scene
    oscAddress: `/scene/${sceneIndex + 1}`,
  })),
];
