name: Deploy
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  macos-deploy:
    name: "macOS Deploy"
    runs-on: "macos-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: 14
      - id: get_version
        uses: battila7/get-version-action@v2
      - uses: elgohr/Github-Release-Action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          title: "${{ steps.get_version.outputs.version }}"