name: Deploy
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  macos-deploy:
    name: "macOS Deploy"
    runs-on: "macos-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: 14
      - name: install dependencies
        run: npm install
      - name: compiling the application
        run: npm run compile
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.KWEENB_REPO_TOKEN }}"
          prerelease: false
          files: |
            bin/*.dmg


